import { FinancialAgent } from "./type";

// Sample data
export const sampleAgents: FinancialAgent[] = [
  {
    id: "1",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "active",
  },
  {
    id: "2",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "offline",
  },
  {
    id: "3",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "offline",
  },
  {
    id: "4",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "active",
  },
  {
    id: "5",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "active",
  },
  {
    id: "6",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "active",
  },
  {
    id: "7",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "active",
  },
  {
    id: "8",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "offline",
  },
  {
    id: "9",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "offline",
  },
  {
    id: "10",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "active",
  },
  {
    id: "11",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "active",
  },
  {
    id: "12",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "active",
  },
  {
    id: "13",
    name: "Financial Agent",
    workflows: 5,
    conversations: 2,
    users: 0,
    files: 1,
    status: "active",
  },
];
