import { Workflow } from "./types";

export const dummyWorkflows: Workflow[] = [
  {
    id: "1",
    name: "D1 Work Flow",
    description: "Lorem ipsum dolor sit amet consectetur.",
    triggers: 2,
    actions: 2,
    schedule: "Never",
    status: "N/A",
    isActive: true,
  },
  {
    id: "2",
    name: "D2 Work Flow",
    description: "Lorem ipsum dolor sit amet consectetur.",
    triggers: 3,
    actions: 1,
    schedule: "Daily",
    status: "Running",
    isActive: true,
  },
  {
    id: "3",
    name: "D3 Work Flow",
    description: "Lorem ipsum dolor sit amet consectetur.",
    triggers: 1,
    actions: 4,
    schedule: "Weekly",
    status: "N/A",
    isActive: false,
  },
  {
    id: "4",
    name: "D4 Work Flow",
    description: "Lorem ipsum dolor sit amet consectetur.",
    triggers: 2,
    actions: 2,
    schedule: "Never",
    status: "N/A",
    isActive: true,
  },
  {
    id: "5",
    name: "D5 Work Flow",
    description: "Lorem ipsum dolor sit amet consectetur.",
    triggers: 4,
    actions: 3,
    schedule: "Monthly",
    status: "Running",
    isActive: true,
  },
  {
    id: "6",
    name: "D6 Work Flow",
    description: "Lorem ipsum dolor sit amet consectetur.",
    triggers: 2,
    actions: 2,
    schedule: "Never",
    status: "N/A",
    isActive: true,
  },
  {
    id: "7",
    name: "D7 Work Flow",
    description: "Lorem ipsum dolor sit amet consectetur.",
    triggers: 1,
    actions: 1,
    schedule: "Never",
    status: "N/A",
    isActive: false,
  },
  {
    id: "8",
    name: "D8 Work Flow",
    description: "Lorem ipsum dolor sit amet consectetur.",
    triggers: 3,
    actions: 2,
    schedule: "Daily",
    status: "Running",
    isActive: true,
  },
  {
    id: "9",
    name: "D9 Work Flow",
    description: "Lorem ipsum dolor sit amet consectetur.",
    triggers: 2,
    actions: 2,
    schedule: "Never",
    status: "N/A",
    isActive: true,
  },
];



